/* ============================================================
   BINKSFILMS — LES FILMS
   ------------------------------------------------------------
   Ne modifie pas ce fichier à la main.
   Ouvre "admin.html", fais tes changements, clique sur
   "Télécharger films.js", puis remplace ce fichier par celui
   que tu viens de télécharger.
   ============================================================ */
window.FILMS_DATA = [
  {
    "slug": "fin-des-temps",
    "yt": "hKaRJtDT1-M",
    "artist": "Saisai",
    "title": "Fin des temps (feat. Boro700)",
    "sortie": "2026-08-14",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "tokio-hotel",
    "yt": "NZ6eu93tG4M",
    "artist": "Fulltrap & Laskiiz",
    "title": "Tokio Hotel",
    "sortie": "2026-06-03",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "fiche-s-2",
    "yt": "USixG_aFCTk",
    "artist": "Saisai",
    "title": "Fiché S 2",
    "sortie": "2026-05-15",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "pain-music-remix",
    "yt": "QVNq4_j283o",
    "artist": "Fono M",
    "title": "Pain Music Remix",
    "sortie": "2026-03-21",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "17h-dans-la-zone-4",
    "yt": "1qXyAMtEhpU",
    "artist": "Fono M",
    "title": "17h dans la Zone 4",
    "sortie": "2025-12-24",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "free-durk",
    "yt": "3U2HE5YxVLo",
    "artist": "Fono M",
    "title": "Free Durk",
    "sortie": "2025-12-13",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "yeah-yeah",
    "yt": "cL8-AhZqWwE",
    "artist": "Fono M",
    "title": "Yeah Yeah",
    "sortie": "2025-12-09",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "la-voix-episode-1",
    "yt": "_4rAF1_ZlJE",
    "artist": "Crimshoot",
    "title": "La Voix — Épisode 1",
    "sortie": "2025-06-06",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "freestyle-6",
    "yt": "V0TB5Sd8mL4",
    "artist": "JDK",
    "title": "Freestyle 6",
    "sortie": "2020-10-31",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "4-4-2",
    "yt": "NFfo80BK5Ow",
    "artist": "Taz",
    "title": "4.4.2",
    "sortie": "2020-02-14",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "mmd",
    "yt": "TeXm8jeKRVY",
    "artist": "JDK",
    "title": "M.M.D",
    "sortie": "2019-10-12",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "sombre-2",
    "yt": "6pxn9l6Ca04",
    "artist": "Brvbus",
    "title": "Sombre 2",
    "sortie": "2018-08-18",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "zoner",
    "yt": "-T2tS9Uc47k",
    "artist": "Ponshox",
    "title": "Zoner",
    "sortie": "2018-05-02",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "z-serie-5",
    "yt": "qj1IAo9qN-8",
    "artist": "Zoupouti",
    "title": "Z Série 5",
    "sortie": "2018-04-18",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  },
  {
    "slug": "gotham",
    "yt": "BSa9e_DVxEE",
    "artist": "4CH",
    "title": "Gotham feat. Codé",
    "sortie": "2018-01-05",
    "type": "Clip",
    "archive": false,
    "poster": "",
    "note": "",
    "lieu": "",
    "tournage": "",
    "credits": [["Réalisation, image & montage", "BINKSFILMS"]],
    "contrechamp": null,
    "bts": []
  }
];
